### ISSUE TITLE
[FEATURE] sketch classification

### ISSUE THREAD

**Issue by taeyoung1005** [taeyoung1005/Boostcamp-AI-tech-7th-Sub-Project#1]
## Background
- Boostcamp 에서 진행한 sketch 이미지 기반 classification 기능 구현

## Todo
- [x] 소개 페이지 구현
- [x] 이미지 업로드 구현
- [ ] 이미지 classification 구현
- [x] prediction 결과 그래프 구현
- [x] classification된 이미지 리스트 구현
- [ ] 실시간 비디오 스트림 classification 구현
