### ISSUE TITLE
[FEATURE] Object detection

### ISSUE THREAD

**Issue by taeyoung1005** [taeyoung1005/Boostcamp-AI-tech-7th-Sub-Project#2]
## Background
- Boostcamp 에서 진행한 재활용 이미지 기반 object detection 기능 구현

## Todo
- [x] 소개 페이지 구현
- [ ] 이미지 업로드 구현
- [ ] 이미지 object detection 구현
- [ ] prediction 결과 그래프 구현
- [ ] detection 된 이미지 리스트 구현
- [ ] 실시간 비디오 스트림 object detection 구현
